#!/usr/bin/env bash

export XDG_CONFIG_HOME="$HOME"/.config
mkdir -p "$XDG_CONFIG_HOME"

nix-env -iA nixpkgs.myPackages

ln -sf "$PWD/.config/nvim" "$XDG_CONFIG_HOME"/nvim
ln -sf "$PWD/.config/lazygit" "$XDG_CONFIG_HOME"/lazygit
ln -sf "$PWD/.config/nixpkgs" "$XDG_CONFIG_HOME"/nixpkgs
ln -sf "$PWD/.oh-my-zsh" "$HOME"/.oh-my-zsh
ln -sf "$PWD/.vimrc" "$HOME"/.vimrc
ln -sf "$PWD/.zshrc" "$HOME"/.zshrc
ln -sf "$PWD/.p10k.zsh" "$HOME"/.p10k.zsh

cd "$PWD" && git submodule update --init --recursive

export PATH="$HOME/.nix-profile/bin:$PATH"
hash -r

nvim --headless "+Lazy! sync" +qa
