#!/usr/bin/env bash

export XDG_CONFIG_HOME="$HOME"/.config
mkdir -p "$XDG_CONFIG_HOME"

ln -sf "$PWD/.config/nixpkgs" "$XDG_CONFIG_HOME"/nixpkgs
nix-env -iA nixpkgs.myPackages

mkdir -p "$HOME/.oh-my-zsh/custom/themes"
ln -sfn "$HOME/.nix-profile/share/zsh-powerlevel10k" "$HOME/.oh-my-zsh/custom/themes/powerlevel10k"

ln -sf "$PWD/.config/nvim" "$XDG_CONFIG_HOME"/nvim
ln -sf "$PWD/.config/lazygit" "$XDG_CONFIG_HOME"/lazygit
ln -sf "$PWD/.oh-my-zsh" "$HOME"/.oh-my-zsh
ln -sf "$PWD/.vimrc" "$HOME"/.vimrc
ln -sf "$PWD/.zshrc" "$HOME"/.zshrc
ln -sf "$PWD/.p10k.zsh" "$HOME"/.p10k.zsh

cd "$PWD" && git submodule update --init --recursive

export PATH="$HOME/.nix-profile/bin:$PATH"
hash -r

PYNVIM_VENV="$HOME/.virtualenvs/neovim"
if [ ! -x "$PYNVIM_VENV/bin/python" ]; then
  mkdir -p "$(dirname "$PYNVIM_VENV")"
  python3 -m venv "$PYNVIM_VENV"
fi
"$PYNVIM_VENV/bin/pip" install --upgrade --quiet pip pynvim

nvim --headless "+Lazy! sync" +qa

ZSH_BIN="$HOME/.nix-profile/bin/zsh"
chsh -s "$ZSH_BIN" "$USER"