#!/bin/sh

# Functions

install_arch() {

    # zsh, oh my zsh
    sudo pacman -S zsh
    sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

    # yay
    sudo pacman -S --needed git base-devel yay

    # hyprland
    sudo pacman -S hyprmod

    # nvm
    git clone https://github.com/lukechilds/zsh-nvm ~/.oh-my-zsh/custom/plugins/zsh-nvm
    nvm install --lts
    nvm use --lts

    # yazi
    sudo pacman -S yazi ffmpeg 7zip jq poppler fd ripgrep fzf zoxide resvg imagemagick
    sudo pacman -S trash-cli

    # uv
    curl -LsSf https://astral.sh/uv/install.sh | sh
    uv python install --default

    # tools
    sudo pacman -S nvtop

    # lua
    sudo pacman -S luajit luarocks

    # nvim
    sudo pacman -S nvim tree-sitter-cli
    git clone https://github.com/nishantpillai5/neovim_vscode_config/ ~/.config/nvim

    uv venv ~/.virtualenvs/neovim --python=3.11 --seed
    ~/.virtualenvs/neovim/bin/python -m pip install -U pynvim
}

install_mac(){
    echo "No bootstrap available for mac"
}

# Main

os_like="unknown"

if [[ "$OSTYPE" == "darwin"* ]]; then
    os_like="mac"
elif [[ "$OSTYPE" == "linux-gnu"* ]]; then
    if [ -f /etc/os-release ]; then
        os_like=$(grep '^ID_LIKE=' /etc/os-release | cut -d= -f2 | tr -d '"')
    fi
fi

case $os_like in
    "arch"|"manjaro")
        install_arch
        ;;
    "mac")
        install_mac
        ;;
    *)
        echo "No bootstrap available for $os_like"
        ;;
esac