#!/bin/sh

os_like=$(grep '^ID_LIKE=' /etc/os-release | cut -d= -f2 | tr -d '"')

if [ "$os_like" = "arch" ]; then

    # zsh, oh my zsh
    sudo pacman -S zsh
    sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

    # yay
    sudo pacman -S --needed git base-devel yay

    # hyprland
    sudo pacman -S hyprmod

    # nvm
    git clone https://github.com/lukechilds/zsh-nvm ~/.oh-my-zsh/custom/plugins/zsh-nvm
    nvm install --lts
    nvm use --lts

    # yazi
    sudo pacman -S yazi ffmpeg 7zip jq poppler fd ripgrep fzf zoxide resvg imagemagick
    sudo pacman -S trash-cli

    # uv
    curl -LsSf https://astral.sh/uv/install.sh | sh

    # tools
    sudo pacman -S nvtop

    # nvim
    sudo pacman -S nvim tree-sitter-cli
    git clone https://github.com/nishantpillai5/neovim_vscode_config/ ~/.config/nvim

elif [ "$os_like" = "mac" ]; then

	echo "No bootstrap available for $os_like"

else

	echo "No bootstrap available for $os_like"

fi
